# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57687e48b380343736d41054be39303b980d1b2385d0de4568ef001a7b5673bb28c9fc83bbdb996735e54f432b091623ec8420f6c3af82d67dec104026e46273

test:
  secret_key_base: 2cd31d0a8935f0efc0942884563e2f6b2a5a86351cf9a8e58ab7ea90dcf31deff6333abf0a720ec345eddc1259f6b2c28f1b38237a27df01e65d7903d5a40784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
